### ISSUE TITLE
inTrees for xgboost

### ISSUE THREAD

**Issue by softwaredeng** [softwaredeng/inTrees#6]

**Comment by qingyuanxingsi** [comment]
Do you support **xgboost** now??

**Comment by softwaredeng** [comment]
@qingyuanxingsi Just added for this version: https://github.com/softwaredeng/inTrees/blob/master/inTrees_1.2.tar.gz . should be on cran soon.

**Comment by softwaredeng** [comment]
@guanxin1121 @khotilov FYI this has been added. thank you for your contribution to this release. You will added to as co-authors of this package.

**Comment by guanxin1121** [comment]
Thank you Houtao for your great work! This package is really useful!
Xin

---------------------------------------------------------------------------------------------------------------------------------
Xin Guan, PhD Candidate
Department of Biomedical Informatics
Arizona State University

**Comment by Chandanpanda** [comment]
Great work. Any ETA for supporting regression in XgBoost? Does it support regression in any other modelling technique yet
